name: "Feature deploy"
description: "Deploy a new version of a fasit feature"
inputs:
  endpoint:
    description: "The fasit endpoint to deploy to"
    required: true
    default: http://10.0.0.42
  chart:
    description: "chart name"
    required: true
  version:
    description: "version"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy.sh
      shell: bash
      env:
        ENDPOINT: ${{ inputs.endpoint }}
        FEATURE_NAME: ${{ inputs.feature_name }}
        CHART: ${{ inputs.chart }}
        VERSION: ${{ inputs.version }}
