name: 'Feature deploy'
description: 'Deploy a new version of a fasit feature'
inputs:
  endpoint:
    description: 'The fasit endpoint to deploy to'
    required: true
    default: http://10.0.0.42

  feature_name:  # id of input
    description: 'feature name'
    required: true
  json:  # id of input
    description: 'json containing body for rollout request - ex {"imageTag": "2"}'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy.sh
      shell: bash
      env:
        ENDPOINT: ${{ inputs.endpoint }}
        FEATURE_NAME: ${{ inputs.feature_name }}
        JSON: ${{ inputs.json }}
